# -*- coding: utf-8 -*-
"""Strace Output to CSV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYz_zw5rirn9PBlXS8PSnQTs3aFF1qfC
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Fundamentals
import matplotlib.pyplot as plt
import seaborn as sns

#getting columns from text file
column_names=['Run Number','Number of Threads']
skip=0
with open('strace_output_combined_2_threads.txt','r') as file:
  #read each line
  for line in file:
    if skip<2:
      skip+=1 #skipping lines which contain '---'/ lines which aren't system call and their count
      continue
    arr=line.split()
    if len(arr) == 6:
      column_names.append(arr[5])
    else:
      column_names.append(arr[4])
    if "write" in line:
      break
df = pd.DataFrame(columns = column_names)


## FOR ALL THREADS

#appending values into dataframe from text file
# for i in range(4,104,4):
#   output_file='strace_output_combined_'+ str(i)+'_threads.txt'
#   run_no=1
#   skip=0
#   values=[run_no,i]
#   with open(output_file,'r') as file:
#     #read each line
#     for line in file:
#       if skip<2:
#         skip+=1 #skipping lines which contain '---'/ lines which aren't system call and their count
#         continue
#       arr=line.split()
#       values.append(arr[3])
#       if "write" in line:
#         run_no+=1
#         df.loc[len(df.index)]=values
#         values=[run_no,i]
#         skip=-2


## FOR SPECIFIC THREADS

selected_threads=[2,4,8,12,32,36,48,52,56,60,64,68,92,96,100]

for i in selected_threads:
  output_file='strace_output_combined_'+ str(i)+'_threads.txt'
  run_no=1
  skip=0
  values=[run_no,i]
  with open(output_file,'r') as file:
    #read each line
    for line in file:
      if skip<2:
        skip+=1 #skipping lines which contain '---'/ lines which aren't system call and their count
        continue
      arr=line.split()
      values.append(arr[3])
      if "write" in line:
        run_no+=1
        df.loc[len(df.index)]=values
        values=[run_no,i]
        skip=-2

#len(values)
#print(values)

#print(df)
#print(df['read'])

df.to_csv('System_calls.csv')